# Generated by Django 4.0.4 on 2022-05-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naslov', models.CharField(max_length=50, unique=True)),
                ('Avtor', models.CharField(max_length=50)),
                ('Zarn', models.CharField(max_length=50)),
                ('Godina', models.IntegerField()),
                ('Kolicina', models.IntegerField()),
                ('Lokacija', models.CharField(max_length=50)),
                ('Izdavac', models.CharField(max_length=50)),
                ('Jazik', models.CharField(max_length=50)),
                ('Strani', models.IntegerField()),
                ('El_ver', models.BooleanField()),
                ('El_path', models.FileField(null=True, upload_to='')),
                ('ISBN', models.CharField(max_length=50)),
                ('Naslov_original', models.CharField(max_length=50, null=True)),
                ('Nabavna_cena', models.FloatField()),
                ('Kaznena_cena', models.FloatField()),
                ('Prevedena', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Clenovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=30)),
                ('Prezime', models.CharField(max_length=30)),
                ('Data_clenstvo', models.DateField()),
                ('Broj_clenska', models.IntegerField(unique=True)),
                ('Telefon', models.IntegerField()),
                ('Adresa', models.CharField(max_length=50)),
                ('Data_ragjanje', models.DateField()),
                ('Aktiven', models.BooleanField()),
                ('Data_platena_clenarina', models.DateField()),
                ('Dali_ima_pozajmeno', models.BooleanField()),
                ('Pozajmena_kniga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.knigi')),
            ],
        ),
    ]
