# Generated by Django 4.0.4 on 2022-05-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clenovi_pozajmena_kniga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clenovi',
            name='Pozajmena_kniga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.knigi'),
        ),
    ]
