# Generated by Django 4.0.4 on 2022-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_clenovi_telefon_alter_knigi_el_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='clenovi',
            name='Data_pozajmuvanje',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clenovi',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
