# Generated by Django 4.0.4 on 2022-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_clenovi_data_pozajmuvanje_clenovi_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clenovi',
            name='Data_pozajmuvanje',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
